name: Final Pipeline

on:
  push:
    branches:
      - main

jobs:
  final-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Linting
        run: |
          poetry run flake8 .
          poetry run isort . --check-only
          poetry run bandit -r .
        continue-on-error: false

      - name: Unit Tests
        run: |
          poetry run pytest tests/unit
        continue-on-error: false

      - name: Packaging
        run: |
          poetry build
          poetry publish --repository test.pypi.org
        continue-on-error: false
        env:
          POETRY_PYPI_TOKEN: ${{ secrets.POETRY_PYPI_TOKEN }}
