name: Final Pipeline

on:
  push:
    branches:
      - main

jobs:
  final-pipeline:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pipx and poetry
        run: |
          python3 -m pip install --upgrade pip
          pip install pipx
          pipx install poetry
          python3 -m pipx ensurepath

      - name: Linting
        run: |
          poetry run flake8 .
          poetry run isort . --check-only
          poetry run bandit -r .
        continue-on-error: false

      - name: Unit Tests
        run: |
          poetry run pytest tests/unit
        continue-on-error: false

      - name: Packaging
        run: |
          poetry build
          poetry publish --repository test.pypi.org
        continue-on-error: false
        env:
          POETRY_PYPI_TOKEN: ${{ secrets.POETRY_PYPI_TOKEN }}
