name: Unit Tests

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Utilisez une version existante comme 3.8 pour initialiser l'image

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        add-path: false  # Ne pas ajouter Python au chemin, car nous avons déjà installé les dépendances

    - name: Run unit tests
      run: |
        pytest tests/unit
