name: Unit Tests

on: fork

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        add-path: true

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        source $HOME/.poetry/env
        poetry --version

    - name: Install dependencies with Poetry
      run: |
        poetry install

    - name: Run unit tests
      run: |
        poetry run pytest tests/unit
